version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: una_health
      DATABASE_USER: user
      DATABASE_PASSWORD: password

  db:
    image: postgres
    environment:
      POSTGRES_DB: una_health
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password # TODO: change this to a secure password
    ports:
      - "5432:5432"
